# Multi-Stage Build
FROM node:18.16.1 AS builder

WORKDIR /app/next-app

ENV NODE_ENV production

COPY next-app /app/next-app
RUN yarn install --frozen-lockfile && yarn build


FROM node:18.16.1 AS release

WORKDIR /app/next-app

ENV NODE_ENV production

COPY --from=builder /app/next-app/.next ./.next
COPY --from=builder /app/next-app/public ./public
COPY --from=builder /app/next-app/node_modules ./node_modules
COPY --from=builder /app/next-app/package.json ./

CMD ["yarn", "start"]
