services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./app/nuxt:/app/nuxt
      - node_modules:/app/nuxt/node_modules
    environment:
      - TZ=${TZ}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-store-dev:/var/lib/postgresql/data
    environment:
      - TZ=${TZ}
      - POSTGRES_MULTIPLE_DATABASES=${DB_NAME},${TEST_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  pgadmin4:
    image: elestio/pgadmin:latest
    ports:
      - "${PGADMIN_PORT}:8080"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - TZ=${TZ}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=8080

volumes:
  node_modules:
  db-store-dev:
  pgadmin:
